### PR TITLE
fix: error on service page

### LINKED ISSUE #922: Error on Service page : `SyntaxError: JSON.parse`
Hi, 
just connected to the My Services page and encountered this error after a few seconds of inactivity:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
 see screenshot :

Image

The browser's console screams:

```cons
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    subscribeToClusterEvents onyxiaApi.ts:842
    subscribeToClusterEvents onyxiaApi.ts:836
onyxiaApi.ts:842:67
    onyxiaApiWithErrorLogging onyxiaApi.ts:949
    AsyncFunctionThrow self-hosted:808
```

which is [here in the code](https://github.com/InseeFrLab/onyxia/blob/main/web/src/core/adapters/onyxiaApi/onyxiaApi.ts#L842).

Thx in advance and Good luck !

### PR DESCRIPTION
**Pull request by ddecrulle**
Wrapped JSON.parse in a try/catch in subscribeToClusterEvents to avoid crashes on malformed SSE chunks. This may happen due to VPN, proxy, or other network interruptions — likely the root cause of @odysseu's report.

Closed #922

### CODE REVIEW

File: web/src/core/adapters/onyxiaApi/onyxiaApi.ts [hunk 1]
```diff
@@ -857,28 +857,34 @@ export function createOnyxiaApi(params: {
...
+                                        return "error";
+                                    default:
+                                        return "info";
+                                }
+                            })(),
+                            originalEvent: event
+                        });
+                    } catch (error) {
+                        console.error("Failed to parse cluster event:", error, part);
+                    }
```
Comment (garronej) [inline web/src/core/adapters/onyxiaApi/onyxiaApi.ts]: Over catch
